"""
email_delivery.py – Sends the generated PDF report via Gmail HTTP API.
Requires 'token.json' generated by gmail_setup.py.
"""

import os
import base64
import logging
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders

from google.auth.transport.requests import Request
from google.oauth2.credentials import Credentials
from google_auth_oauthlib.flow import InstalledAppFlow
from googleapiclient.discovery import build
from googleapiclient.errors import HttpError

from config import GMAIL_ADDRESS, RECIPIENTS

logger = logging.getLogger(__name__)

SCOPES = ['https://www.googleapis.com/auth/gmail.send']

BODY_TEMPLATE = """\
Dear Recipient,

Your Morning Market Brief for {date_str} is ready. Please find the hedge-fund-style \
market intelligence report attached as a PDF.

The brief covers:
  • Executive Summary & Market Tone
  • Macro & Market Environment
  • Sector Breakdown (Tech, Energy, Healthcare, Financials, Consumer)
  • Company-Specific Signals
  • Catalyst Tracker
  • Trade Ideas
  • Risk Factors & Outlier Signals

This report is produced by the Apeiro Investments automated intelligence system and is \
intended for educational and paper trading purposes only. Not financial advice.

Best regards,
Apeiro Investments – Research System
"""

def get_gmail_service():
    """Load credentials and build the Gmail service."""
    creds = None
    if os.path.exists('token.json'):
        creds = Credentials.from_authorized_user_file('token.json', SCOPES)
    
    # Refresh if expired
    if creds and creds.expired and creds.refresh_token:
        creds.refresh(Request())
    
    if not creds or not creds.valid:
        logger.error("[Email] No valid 'token.json' found. Run 'python gmail_setup.py' first.")
        return None
        
    return build('gmail', 'v1', credentials=creds)

def send_report(pdf_path: str) -> bool:
    """
    Email the PDF at `pdf_path` via Gmail HTTP API.
    Returns True on success, False on failure.
    """
    if not RECIPIENTS:
        logger.error("[Email] No RECIPIENTS configured in config.py. Aborting send.")
        return False

    if not os.path.isfile(pdf_path):
        logger.error(f"[Email] PDF not found at {pdf_path}. Aborting send.")
        return False

    service = get_gmail_service()
    if not service:
        return False

    date_str = datetime.now().strftime("%A, %B %d, %Y")
    subject = f"Morning Market Brief — {datetime.now().strftime('%B %d, %Y')}"

    # Create the message
    msg = MIMEMultipart()
    msg["From"] = GMAIL_ADDRESS
    msg["To"] = ", ".join(RECIPIENTS)
    msg["Subject"] = subject
    msg.attach(MIMEText(BODY_TEMPLATE.format(date_str=date_str), "plain"))

    # Attach PDF
    with open(pdf_path, "rb") as f:
        part = MIMEBase("application", "octet-stream")
        part.set_payload(f.read())
    encoders.encode_base64(part)
    pdf_filename = os.path.basename(pdf_path)
    part.add_header("Content-Disposition", f'attachment; filename="{pdf_filename}"')
    msg.attach(part)

    # Encode as base64url
    raw_message = base64.urlsafe_b64encode(msg.as_bytes()).decode()
    create_message = {"raw": raw_message}

    try:
        logger.info("[Email] Sending via Gmail API…")
        send_result = service.users().messages().send(userId="me", body=create_message).execute()
        logger.info(f"[Email] Report sent successfully! Message ID: {send_result.get('id')}")
        return True
    except HttpError as error:
        logger.error(f"[Email] An HTTP error occurred: {error}")
        return False
    except Exception as exc:
        logger.error(f"[Email] Failed to send email: {exc}")
        return False
